Custom1
AndreyShpakXB/webix-customs pull request #1
Opened 2021-09-29 20:18 UTC by AndreyShpakXB

2021-09-29 21:10 UTC, HelgaListopad requested changes

2021-09-29 21:10 UTC, HelgaListopad commented on js/tsbutton/button.js
> +                    $$("list").parse(items);
Переиспользуем одни и те же данные => `webix.copy`. В `data` листа в том числе.

2021-09-29 21:10 UTC, HelgaListopad commented on js/tsbutton/button.js
> +                    $$("list").parse(items);
Вообще в задании предлагалось считать последовательные IDs за критерий для "сброшенной сортировки", а в остальнх случаях вызывать `sort` по другим полям.
> Note that there’s no unsort for Webix data widgets. For these needs you can sort data by some index column  - here it can be “id”. 

Но не вижу причин считать сделанное здесь ошибкой в данном случае (не зря же id у тебя в данных изначально перепутаны)

2021-09-30 05:54 UTC, VeraOrekhXB requested changes

2021-09-30 05:54 UTC, VeraOrekhXB commented on js/mixins/tsbutton.js
> +    if (!config.states) {
Здесь также можно добавить проверку на то, является ли данное свойство объектом

2021-09-30 05:54 UTC, VeraOrekhXB commented on js/mixins/tsbutton.js
> +    config.css = config.colors[0];
На случай, если данного свойства нет в объекте, можно выставить дефолтное значение
И вывести сообщение об ошибке в конфиге

2021-09-30 05:54 UTC, VeraOrekhXB commented on js/mixins/tsbutton.js
> +    this.attachEvent("onItemClick", function(id, e){
@HelgaListopad, нужно ли вызывать detachEvent для этого ивента?

2021-09-30 07:01 UTC, AndreyShpakXB commented on js/mixins/autoform.js
> +            { view:"button", value:"Cancel", inputWidth:150, click:formCancelClick },
исправил

2021-09-30 07:02 UTC, AndreyShpakXB commented on js/mixins/autoform.js
> +            config.elements.push({ view:"text", label:value, name:value.toLowerCase() });
исправил

2021-09-30 07:08 UTC, AndreyShpakXB commented on js/tsbutton/button.js
> +                    $$("list").parse(items);
поправил

2021-09-30 07:43 UTC, AndreyShpakXB commented on js/mixins/tsbutton.js
> +    if (!config.states) {
добавил

2021-09-30 07:43 UTC, AndreyShpakXB commented on js/mixins/tsbutton.js
> +    config.css = config.colors[0];
добавил

2021-09-30 08:15 UTC, AndreyShpakXB commented on js/mixins/tsbutton.js
> +        this.$view.className = this.$view.className.replace(' ' + name, '');
поправил

2021-09-30 08:15 UTC, AndreyShpakXB commented on js/mixins/autoform.js
> +        config.fields.forEach(value => {
поправил

2021-09-30 08:17 UTC, VeraOrekhXB approved these changes

2021-09-30 08:51 UTC, HelgaListopad commented on js/mixins/tsbutton.js
> +    this.attachEvent("onItemClick", function(id, e){
Нет, события, прикреплённые к самому компоненту, отдельным кодом детачить не надо - они разрушатся вместе с компонентом.
Но если бы в компоненте использовались обработчики глобальных событий (`webix.attachEvent("onClick", e => {})`), то вот такое надо было бы обязательно детачить в событии `onDestruct`

2021-09-30 09:04 UTC, HelgaListopad approved these changes

2021-09-30 09:11 UTC, merged